version: 2

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test --passWithNoTests

      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy-to-heroku:
    docker:
      - image: circleci/node:10.20.0
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
  deploy-to-heroku:
    jobs:
    - ci
    - heroku/deploy-via-git:
        requires:
          - ci
        filters:
          branches:
            only: master

orbs:
  heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config